(function(g){
 const U=g.POS.utils;
 const medios=['EFECTIVO','MERCADO_PAGO','TRANSFERENCIA','DEBITO','TARJETA_CREDITO'];
 function root(localId){return g.POS.paths.path(localId,'cash');}
 async function recordSale(localId,orderKey,order,medio,propina=0,user=''){if(!medios.includes(medio))throw new Error('Medio de pago inválido');const id='venta_'+Date.now()+'_'+Math.random().toString(36).slice(2,6);const row={id,idComanda:order.id||orderKey,orderKey,fecha:Date.now(),canal:order.canal||order.mesaBase||'',mesa:order.mesa||'',cliente:order.cliente||'',total:Number(order.total_cobrado||order.total||0),medioPago:medio,propina:Number(propina||0),usuario:user||g.POS.session?.current?.()?.nombre||'Sistema',estado:'CONFIRMADA'};await g.POS.db.ref(`${root(localId)}/ventas/${id}`).set(row);await g.POS.db.ref(`${g.POS.orders.ordersPath(localId)}/${orderKey}`).update({estado:'COBRADA',medioPago:medio,propina:row.propina,total_cobrado:row.total,cobradaEn:row.fecha,cobradaPor:row.usuario});if(row.propina>0)await g.POS.db.ref(`${root(localId)}/propinas`).push({monto:row.propina,medioPago:medio,mesa:row.mesa,timestamp:row.fecha,usuario:row.usuario});await g.POS.audit?.log(localId,'COBRAR','CAJA',{orderKey,total:row.total,medio});return row;}
 async function movement(localId,tipo,concepto,importe,medio='EFECTIVO',categoria='GENERAL',usuario=''){const id='mov_'+Date.now()+'_'+Math.random().toString(36).slice(2,6);const row={id,tipo,categoria,concepto,importe:Number(importe||0),medioPago:medio,usuario:usuario||g.POS.session?.current?.()?.nombre||'Sistema',fecha:Date.now(),estado:'CONFIRMADO'};await g.POS.db.ref(`${root(localId)}/movimientos/${id}`).set(row);const bucket=tipo==='COMPRA'?'compras':tipo==='PAGO'?'pagos':tipo==='GASTO'?'gastos':null;if(bucket)await g.POS.db.ref(`${root(localId)}/${bucket}/${id}`).set(row);await g.POS.audit?.log(localId,'MOVIMIENTO_CAJA','CAJA',row);return row;}
 async function saveZ(localId,data){const id='Z_'+Date.now();const row={id,numeroZ:data.numeroZ||'',fecha:Number(data.fecha||Date.now()),totalZ:Number(data.totalZ||0),neto:Number(data.neto||0),iva:Number(data.iva||0),desdeTicket:data.desdeTicket||'',hastaTicket:data.hastaTicket||'',terminal:data.terminal||'',observacion:data.observacion||'',usuario:data.usuario||g.POS.session?.current?.()?.nombre||'Sistema',estado:'REGISTRADO'};await g.POS.db.ref(`${root(localId)}/cierres_z/${id}`).set(row);await g.POS.audit?.log(localId,'CARGAR_CIERRE_Z','CAJA',{id,numeroZ:row.numeroZ,totalZ:row.totalZ});return row;}
 async function summary(localId,from=U.todayStart(),to=Date.now()){const s=await g.POS.db.ref(root(localId)).once('value'),d=s.val()||{};const within=x=>{const t=Number(x.fecha||x.timestamp||x.cobradaEn||0);return t>=from&&t<=to};const sales=Object.values(d.ventas||{}).filter(within),moves=Object.values(d.movimientos||{}).filter(within),props=Object.values(d.propinas||{}).filter(within),zs=Object.values(d.cierres_z||{}).filter(within);const byPayment=Object.fromEntries(medios.map(m=>[m,0]));sales.forEach(v=>byPayment[v.medioPago]=(byPayment[v.medioPago]||0)+Number(v.total||0));const ventas=sales.reduce((a,v)=>a+Number(v.total||0),0),gastos=moves.filter(m=>['GASTO','PAGO','COMPRA','RETIRO'].includes(m.tipo)).reduce((a,m)=>a+Number(m.importe||0),0),ingresos=moves.filter(m=>m.tipo==='INGRESO').reduce((a,m)=>a+Number(m.importe||0),0),propinas=props.reduce((a,p)=>a+Number(p.monto||0),0);return{sales,moves,zs,byPayment,ventas,gastos,ingresos,propinas,saldoOperativo:ventas+ingresos-gastos};}
 async function reconcileZ(localId,z){const day=new Date(z.fecha);day.setHours(0,0,0,0);const from=day.getTime(),to=from+86400000-1;const sm=await summary(localId,from,to),dif=sm.ventas-Number(z.totalZ||0);const row={fecha:Date.now(),fechaZ:z.fecha,numeroZ:z.numeroZ,ventaSistema:sm.ventas,totalZ:Number(z.totalZ||0),diferencia:dif,estado:Math.abs(dif)<1?'OK':'REVISAR'};await g.POS.db.ref(`${root(localId)}/conciliaciones`).push(row);return row;}
 g.POS={...(g.POS||{}),cash:{medios,root,recordSale,movement,saveZ,summary,reconcileZ}};
})(window);
